### ISSUE TITLE
New diacritic markup feature doesn't seem to be working

### ISSUE THREAD

**Issue by davem2** [wf49670/ppgen#85]
Hey Walt,

I tried to make use of the new diacritic markup function in ppgen and it's not working for me. I believe I'm using the command properly (added a .cv to the top of my source file). 

During processing I see the messages that replacements are occuring, but the output files contain unconverted diacritic markup.

I also tried using the --filter command and it causes ppgen to crash

Here is a copy of the source file I've been using: https://dl.dropboxusercontent.com/u/59728548/p-src.txt

**Comment by wf49670** [comment]
On 3/1/2015 5:20 PM, davem2 wrote:
>
> Hey Walt,
>
> I tried to make use of the new diacritic markup function in ppgen and 
> it's not working for me. I believe I'm using the command properly 
> (added a .cv to the top of my source file).
>
> During processing I see the messages that replacements are occuring, 
> but the output files contain unconverted diacritic markup.
>
> I also tried using the --filter command and it causes ppgen to crash
>
> Here is a copy of the source file I've been using: 
> https://dl.dropboxusercontent.com/u/59728548/p-src.txt
>

Thanks; I'm sorry to hear that, of course, but I'll take a look. 
Hopefully something simple to fix.

Regards,
Walt

**Comment by wf49670** [comment]
On 3/1/2015 5:20 PM, davem2 wrote:
>
> Hey Walt,
>
> I tried to make use of the new diacritic markup function in ppgen and 
> it's not working for me. I believe I'm using the command properly 
> (added a .cv to the top of my source file).
>
> During processing I see the messages that replacements are occuring, 
> but the output files contain unconverted diacritic markup.
>
> I also tried using the --filter command and it causes ppgen to crash
>
> Here is a copy of the source file I've been using: 
> https://dl.dropboxusercontent.com/u/59728548/p-src.txt
>

Fixed in development 3.47j.

Dumb error while doing some refactoring. Sorry.

-- 
Walt

**Comment by wf49670** [comment]
On 3/1/2015 5:20 PM, davem2 wrote:
>
> Hey Walt,
>
> I tried to make use of the new diacritic markup function in ppgen and 
> it's not working for me. I believe I'm using the command properly 
> (added a .cv to the top of my source file).
>
> During processing I see the messages that replacements are occuring, 
> but the output files contain unconverted diacritic markup.
>
> I also tried using the --filter command and it causes ppgen to crash
>
> Here is a copy of the source file I've been using: 
> https://dl.dropboxusercontent.com/u/59728548/p-src.txt
>

Also pushed into Master 3.47.2 for those who don't want the development 
branch.
